FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

#Ensure the "node" user owns the application files
RUN chown -R node:node /app

# Switch to the built-in non-root "node" user
USER node

EXPOSE 3000
CMD ["npm", "start"]